language: c

script:
  - bash -x -c "echo -e 'Last changes\n ' && cat Changes"
  - python buildgst.py --use-hashes --install-depencies -t ges -t gnl


notifications:
  irc:
      channels:
          - "chat.freenode.net#pitivi"
      on_success: [change] # default: always
      on_failure: [change] # default: always

