#!/usr/bin/python

import datetime
import time
import platform
import os
import sys
import glob
import shutil


def message(msg):
    sys.stdout.write(msg + '\n')
    sys.stdout.flush()


MAX_BUNDLE_DAYS = 30


arch = platform.machine()
if arch.endswith('86'):
    arch = "x86"
    arch_folder_name = "32bits"
else:
    arch_folder_name = "64bits"

if len(sys.argv) < 2 or "release" not in sys.argv:
    bundles_dir = "/mnt/bundles/daily/"
else:
    bundles_dir = "/mnt/bundles/releases/"

archives_dir = os.path.join(bundles_dir, arch_folder_name, "archives")

def cleanup_bundles(to_archive):
    for f in to_archive:
        message("Archiving %s into %s" % (f, archives_dir))
        shutil.move(f, os.path.join(archives_dir,
                    time.strftime("%Y%m%d-%H%M%S") + "-" + os.path.basename(f)))

    # message("Cleaning up old bundles")
    # now = time.time()
    # for f in os.listdir(archives_dir):
        # f = os.path.join(archives_dir, f)
        # last_modification = os.path.getmtime(f)
        # age = (now - last_modification) / 86400
        # if age > MAX_BUNDLE_DAYS:
        # message("Deleting file %s, it is %d days old" % (f, age))
        # os.remove(f)


version = "0.95"
if len(sys.argv) == 2:
    version_name = sys.argv[1]
else:
    version_name = "latest"

path = os.environ["PATH"]
os.environ["PATH"] = "%s:%s" % (path, os.path.expanduser("~/bin"))
cerbero_folder = os.path.expanduser("~/devel/cerbero")

cerbero_default_branch = "origin/1.6"
tarball_name = bundles_dir + arch_folder_name + "/" + "pitivi-" + version_name + "-" + arch + ".tar.xz"

bundling_dir = os.path.expanduser("~/pitivi/bundling/")
os.system('mkdir -p %s' % bundling_dir)

open("/root/.cerbero/cerbero.cbc", 'w').write("""
use_ccache=True
variants = ['python3', 'gtk3']
recipes_commits = {
    "pitivi": "RELEASE-0_95_0",
    "gst-editing-services-1.0-static": "origin/1.6",
    "gst-editing-services-1.0": "origin/1.6",
    "gst-libav-1.0-static": "origin/1.6",
    "gst-libav-1.0": "origin/1.6",
    "gst-plugins-bad-1.0-static": "origin/1.6",
    "gst-plugins-bad-1.0": "origin/1.6",
    "gst-plugins-base-1.0-static": "origin/1.6",
    "gst-plugins-base-1.0": "origin/1.6",
    "gst-plugins-good-1.0-static": "origin/1.6",
    "gst-plugins-good-1.0": "origin/1.6",
    "gst-plugins-ugly-1.0-static": "origin/1.6",
    "gst-plugins-ugly-1.0": "origin/1.6",
    "gst-python-1.0": "origin/1.6",
    "gst-rtsp-server-1.0": "origin/1.6",
    "gst-validate": "origin/1.6",
    "gstreamer-1.0-static": "origin/1.6",
    "gstreamer-1.0": "origin/1.6",
}
""")


message("Using /root/.cerbero/cerbero.cbc:")
os.system("cat /root/.cerbero/cerbero.cbc")

commands = ["cd %s && git remote update && git reset --hard %s" % (cerbero_folder, cerbero_default_branch),
            "echo $(git show --summary)",
            "cerbero bootstrap --build-tools-only",
            "cerbero fetch --reset-rdeps --full-reset pitivi",
            "cerbero package pitivi --force --linux-bundle --output-dir %(bundling_dir)s --no-devel",
            "mv pitivi-%(version)s-%(arch)s pitivi-%(version)s-%(arch)s-%(date)s",
            "ln -s pitivi-%(version)s-%(arch)s-%(date)s pitivi-%(version)s-%(arch)s",
            "tar -Jcf %(tarball_name)s.tmp pitivi-%(version)s-%(arch)s pitivi-%(version)s-%(arch)s.md5sum pitivi-%(version)s-%(arch)s-%(date)s",
            "rm -Rf %(bundling_dir)s/*"]

os.chdir(bundling_dir)
to_archive = glob.glob(os.path.join(bundles_dir, arch_folder_name) + "/pitivi-*.tar.*")

date = datetime.datetime.now().strftime("%Y-%m-%d_%H%M")
for command in commands:
    command = command % {"arch": arch,
                         "version": version,
                         "version_name": version_name,
                         "arch_folder_name": arch_folder_name,
                         "bundles_dir": bundles_dir,
                         "bundling_dir": bundling_dir,
                         "archives_dir": archives_dir,
                         "tarball_name": tarball_name,
                         "date": date,
                         }
    message("Launching %s" % command)

    res = os.system(command)
    if res != 0:
        message("FAILLURE!")
        exit(1)

cleanup_bundles(to_archive)
os.rename(tarball_name + ".tmp", tarball_name)
