#!/usr/bin/python

import datetime
import platform
import os
import sys

def message(msg):
    sys.stdout.write(msg + '\n')
    sys.stdout.flush()


arch = platform.machine()
if arch.endswith('86'):
    arch = "x86"
    arch_folder_name = "32bits"
else:
    arch_folder_name = "64bits"


version="0.93-beta"
if len(sys.argv) == 2:
    version_name = sys.argv[1]
else:
    version_name = datetime.datetime.now().strftime("%Y-%m-%d_%H:%M")

path = os.environ["PATH"]
os.environ["PATH"] =  "%s:%s" %(path, os.path.expanduser("~/bin"))
cerbero_folder = os.path.expanduser("~/devel/cerbero")

cerbero_default_branch = "thiblahute/master"
commands = ["cd %s && git remote update && git reset --hard %s" % (cerbero_folder, cerbero_default_branch),
            "echo $(git show --summary)",
            "cerbero bootstrap --build-tools-only",
            "cerbero fetch --reset-rdeps --full-reset pitivi",
            "cerbero package pitivi --force --linux-bundle --no-devel --output-dir %s" % os.path.expanduser('~'),
            "tar -cf pitivi-%(version_name)s-%(arch)s.tar pitivi-%(version)s-%(arch)s pitivi-%(version)s-%(arch)s.md5sum",
            "md5sum pitivi-%(version_name)s-%(arch)s.tar > pitivi-%(version_name)s-%(arch)s.tar.md5sum",
            "mv pitivi-%(version_name)s-%(arch)s.tar ~/Dropbox/Public/bundles/%(arch_folder_name)s",
            "mv pitivi-%(version_name)s-%(arch)s.tar.md5sum ~/Dropbox/Public/bundles/%(arch_folder_name)s",
            "date > ~/Dropbox/Public/bundles/%(arch_folder_name)s/pitivi-%(version_name)s-%(arch)s.tar.date",
            "rsync -v ~/Dropbox/Public/bundles/%(arch_folder_name)s/* amazon:/home/ubuntu/pitivi-fundraising/www/website/static/websitestatic/"]

os.chdir(os.environ["HOME"])
for command in commands:
    command = command % {"arch": arch, "version": version,
                         "version_name": version_name,
                         "arch_folder_name": arch_folder_name,
                         }
    message("Launching %s" % command)

    res = os.system(command)
    if res != 0:
       message("FAILLURE!")
       exit(1)
