#!/bin/bash

export APPDIR="/app/"
export CPPFLAGS="-I${APPDIR}/include ${CPPFLAGS}"
export GI_TYPELIB_PATH="${APPDIR}/lib/girepository-1.0"
export PYTHON="python3"
export GTK_DATA_PREFIX="${APPDIR}"
export CXXFLAGS="-I${APPDIR}/include ${CXXFLAGS}"
export PATH="${APPDIR}/bin${PATH:+:$PATH}:/usr/local/bin:/usr/bin:/bin"
export GIO_EXTRA_MODULES="${APPDIR}/lib/gio/modules"
export LD_LIBRARY_PATH="${APPDIR}/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export XDG_DATA_DIRS="${APPDIR}/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}:/usr/local/share:/usr/share"
export GST_PLUGIN_SCANNER_1_0="${APPDIR}/libexec/gstreamer-1.0/gst-plugin-scanner"
export LDFLAGS="-L${APPDIR}/lib ${LDFLAGS}"
export GTK_PATH="${APPDIR}/lib/gtk-3.0"
export GST_REGISTRY="${HOME}/.cache/gstreamer-1.0/pitivi-bundle-registry"
export GST_REGISTRY_1_0="${HOME}/.cache/gstreamer-1.0/pitivi-bundle-registry"
export PYTHONPATH="${APPDIR}/lib/python3.3/site-packages:${APPDIR}/lib/pitivi/python/:${PYTHONPATH:+:$PYTHONPATH}"
export GST_PLUGIN_SCANNER="${APPDIR}/libexec/gstreamer-0.10/gst-plugin-scanner"
export PKG_CONFIG_PATH="${APPDIR}/lib/pkgconfig:${APPDIR}/share/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}"
export GSETTINGS_SCHEMA_DIR="${APPDIR}/share/glib-2.0/schemas/:${GSETTINGS_SCHEMA_DIR}"
export XDG_CONFIG_DIRS="${APPDIR}/etc/xdg${XDG_CONFIG_DIRS:+:$XDG_CONFIG_DIRS}:/etc/xdg"
export PYTHONHOME="${APPDIR}"
export GTK_THEME="Adwaita:dark"
export CFLAGS="-I${APPDIR}/include ${CFLAGS}"


# Try to discover plugins only once
LOCKFILE="/tmp/pitivi-bundle.lock"
if [ -e $LOCKFILE ]
then
    PID=$(cat $LOCKFILE)
    if kill -0 $PID 2> /dev/null
    then
        echo "$? $PID pitivi already running -> exiting"
        exit 1
    else
        echo "Stalled process $PID allow restarting"
    fi
fi
echo $$ > $LOCKFILE

PLUGINS_SYMLINK=${HOME}/.cache/gstreamer-1.0/pitivi-gstplugins
rm ${PLUGINS_SYMLINK} > /dev/null 2>&1
ln -s ${APPDIR}/lib/gstreamer-1.0/ ${PLUGINS_SYMLINK}
if [ $? -ne 0 ]; then
    export GST_PLUGIN_PATH=${APPDIR}/lib/gstreamer-1.0/
else
    export GST_PLUGIN_PATH=${PLUGINS_SYMLINK}
fi

trap 'ECODE=$?;
      echo "[statsgen] Removing lock. Exit: ${ETXT[ECODE]}($ECODE)" >&2
      rm "${PLUGINS_SYMLINK}" "${LOCKFILE}"' 0

export GDK_PIXBUF_MODULE_FILE=/app/share/gdk-pixbuf-loader.cache
if [[ -e /etc/fonts/fonts.conf && -z "$FONTCONFIG_FILE" ]]
then
    export FONTCONFIG_FILE=/etc/fonts/fonts.conf
fi

cd ${APPDIR}
${APPDIR}/bin/pitivi $*
# Cleaning up the link to gstplugins
rm ${PLUGINS_SYMLINK}

